# Generated by Django 3.0 on 2024-04-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
    ]
