# Generated by Django 4.2.11 on 2024-04-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_answer_id_alter_questions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='ans',
            field=models.ManyToManyField(blank=True, to='questions.answer'),
        ),
    ]
