# Generated by Django 3.0 on 2023-02-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_alter_aquiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquiz',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aquiz',
            name='required_score_to_pass',
            field=models.IntegerField(help_text='Requ++ired score to pass'),
        ),
    ]
